### Register Customer
POST {{baseUrl}}/api/v1/auth/register/customer
Content-Type: application/json

{
  "name": "John Doe",
  "phoneNumber": "+1233563890",
  "password": "securePassword123"
}

### Register Seller
POST {{baseUrl}}/api/v1/auth/register/seller
Content-Type: application/json

{
  "name": "{{ $random.alphabetic(7) }}",
  "phoneNumber": {{$random.integer(10, 1000)}},
  "password": "securePassword123"
}

### Login
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json

{
  "phoneNumber": "+1233563890",
  "password": "securePassword123"
}

> {% client.global.set("accessToken", response.body.accessToken); %}



### Refresh Token
POST http://localhost:8080/api/v1/auth/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ5YWR3eS1zZXJ2aWNlIiwic3ViIjoiNjc5IiwiaWQiOjEyLCJleHAiOjE3NzA2NTI1OTYsInR5cGUiOiJyZWZyZXNoIiwiaWF0IjoxNzY4MDYwNTk2fQ.ZAmO8t2NDDRvWNzRyaFaJ4-lAx5zjP89A1FryRLCN9M"
}
