### Register Customer
POST {{baseUrl}}/api/v1/auth/register/customer
Content-Type: application/json

{
  "name": "John Doe",
  "phoneNumber": "+1234567890",
  "password": "securePassword123"
}

### Register Seller
POST {{baseUrl}}/api/v1/auth/register/seller
Content-Type: application/json

{
  "name": "John Doe",
  "phoneNumber": "+1234567811",
  "password": "securePassword123"
}

### Login
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "phoneNumber": "+1234567892",
  "password": "securePassword123"
}


### Refresh Token
POST http://localhost:8080/api/v1/auth/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ5YWR3eS1zZXJ2aWNlIiwic3ViIjoiKzEyMzQ1Njc4OTAiLCJpZCI6MSwiZXhwIjoxNzcwNDU3OTc5LCJ0eXBlIjoicmVmcmVzaCIsImlhdCI6MTc2Nzg2NTk3OX0.znxKEQ140qImejX-FOzkD7YWEs3yZBzFuvTAmj9jdZk"
}
