### Create a product
POST {{baseUrl}}/api/v1/products
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": {
    "ar": "{{$random.commerce.productName}}",
    "en": "{{$random.commerce.productName}}"
  },
  "description": {
    "ar": "{{$random.shakespeare.asYouLikeItQuote}}",
    "en": "{{$random.shakespeare.asYouLikeItQuote}}"
  },
  "images": [
  "{{$random.internet.url}}",
  "{{$random.internet.url}}",
  "{{$random.internet.url}}",
  "{{$random.internet.url}}",
  "{{$random.internet.url}}"
  ],
  "price": {{$random.commerce.price}},
  "categoryId": 1
}

### Create Product
GET {{baseUrl}}/api/v1/products/2
Authorization: Bearer {{accessToken}}


### Update Product's visbility
PATCH {{baseUrl}}/api/v1/products/2/visibility
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "visible": true
}

